name: flask-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - Flask==3.0.2
      - Flask-Login==0.6.3
      - SQLAlchemy==2.0.25
      - Werkzeug==3.0.1
      - reportlab==4.0.9
